"""Добавление каскадного удаления для media при удалении tweets

Revision ID: dbbef938a8ff
Revises: 9f19377a211e
Create Date: 2024-12-19 15:09:12.512800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbef938a8ff'
down_revision: Union[str, None] = '9f19377a211e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('media_tweet_id_fkey', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'tweets', ['tweet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_tweet_id_fkey', 'media', 'tweets', ['tweet_id'], ['id'])
    # ### end Alembic commands ###
